version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml",
    "proton-mail.sh",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "proton-mail.desktop",
]
SPDX-FileCopyrightText = "Proton AG"
SPDX-License-Identifier = "GPL-3.0-or-later"
